#!/opt/bin/sh

ln -sf /etc/TZ /opt/etc/TZ
export PATH=/opt/sbin:/opt/bin:$PATH
export LANG='ru_RU.UTF-8'
export LC_ALL='ru_RU.UTF-8'
unset LD_LIBRARY_PATH
unset LD_PRELOAD
unset LD_BIND_NOW
unset TZ

case $(mount | grep 'on /opt' | cut -d ' ' -f 5) in
    ext2|ext3)
	logger -t installer 'Info: Раздел пригоден для установки.'
    ;;
    *ntfs*)
	logger -t installer 'Info: Раздел NTFS! атрибуты "пользователь:группа" могут не поддерживаться.'
	logger -t installer 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3.'
    ;;
    *hfs*)
	logger -t installer 'Info: Раздел с HFS! (!не тестировалось!).'
	logger -t installer 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3.'
    ;;
    *)
        logger -t installer 'Critical error: Используйте накопитель с файловой системой ext2/ext3. Отменяем...'
	exit 1
    ;;
esac

logger -t installer '[1/5] Начало развёртывания системы Entware-Keenetic...'


logger -t installer '[2/5] Обновление списка пакетов...'
opkg update

if [ $? -eq 0 ] ; then
    logger -t installer 'Info: Список пакетов обновлен'
  else
    logger -t installer 'Warning: Ошибка загрузки? Нет соединения с интернет? Сервер не работает?'
    logger -t installer 'Обновите позже. Продолжим...'
fi

ldconfig > /dev/null 2>&1

# теперь выставляет права
# Fix for multiuser environment
chmod 777 /opt/tmp

logger -t installer '[3/5] Генерация SSH-ключей...'

    rm /opt/etc/dropbear/dropbear_ecdsa_host_key
    dropbearkey -t ecdsa -f /opt/etc/dropbear/dropbear_ecdsa_host_key > /dev/null &
    while [ ! -z "$(pidof dropbearkey)" ] ; do
	sleep 2
	echo -n '.'
    done
    logger -t installer "Info: Ключ ecdsa создан"

    rm /opt/etc/dropbear/dropbear_rsa_host_key
    dropbearkey -t rsa -f /opt/etc/dropbear/dropbear_rsa_host_key -s 1024 > /dev/null &
    while [ ! -z "$(pidof dropbearkey)" ] ; do
	sleep 2
	echo -n '.'
    done
    logger -t installer "Info: Ключ rsa создан"

mv -f /opt/home/* /opt/etc/init.d

logger -t installer '[4/5] Установка Entware-Keenetic завершена!'
logger -t installer 'Запуск dropbear...'
dropbear -p 22 -a

logger -t installer '[5/5] Настройка сценария запуска для прошивки NDMS...'
ndmq -p 'opkg initrc /opt/etc/init.d/rc.unslung'
ndmq -p 'system configuration save'

logger -t installer 'Готово!!!'
logger -t installer 'Можно открыть SSH-сессию для соединения с устройством (логин:пароль -> root:zyxel).'
rm $0
