#!/opt/bin/sh

ln -sf /etc/TZ /opt/etc/TZ
export PATH=/opt/sbin:/opt/bin:$PATH
export LANG='ru_RU.UTF-8'
export LC_ALL='ru_RU.UTF-8'
unset LD_LIBRARY_PATH
unset LD_PRELOAD
unset LD_BIND_NOW
unset TZ

case $(mount | grep 'on /opt' | cut -d ' ' -f 5) in
    ext2|ext3)
	logger -t installer 'Info: Раздел пригоден для установки.'
    ;;
    *ntfs*)
	logger -t installer 'Info: Раздел NTFS! атрибуты "пользователь:группа" могут не поддерживаться.'
	logger -t installer 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3.'
    ;;
    *hfs*)
	logger -t installer 'Info: Раздел с HFS! (!не тестировалось!).'
	logger -t installer 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3.'
    ;;
    *)
        logger -t installer 'Critical error: Используйте накопитель с файловой системой ext2/ext3. Отменяем...'
	exit 1
    ;;
esac

logger -t installer '[1/5] Начало развёртывания системы Entware-Keenetic...'

# This is for opkg only. The other folders will be created from opt-ndmsv2 package
# Только для opkg. Остальные папки будут созданы пакетом opt-ndmsv1/2
logger -t installer 'Info: Создание папок...'

for folder in lib/opkg tmp var/lock; do
    mkdir -p /opt/$folder
done

logger -t installer '[2/5] Загрузка и установка базовых пакетов...'
opkg update
opkg install opt-ndmsv2 dropbear ndmq

# дабы варнингами не пугать
opkg install busybox > /dev/null 2>&1

# слип, чтоб инфо не затерялось
if [ $? -eq 0 ] ; then
    sleep 5s && logger -t installer 'Info: Установка пакетов прошла успешно! Продолжаем...'
  else
    logger -t installer 'Critical error: Ошибка загрузки? Нет соединения с интернетом? Сервер не работает?'
    logger -t installer 'Выход из установки...'
    exit 1
fi

ldconfig > /dev/null 2>&1

# теперь выставляет права
# Fix for multiuser environment
chmod 777 /opt/tmp

logger -t installer '[3/5] Генерация SSH-ключей...'

    rm /opt/etc/dropbear/dropbear_ecdsa_host_key
    dropbearkey -t ecdsa -f /opt/etc/dropbear/dropbear_ecdsa_host_key > /dev/null &
    while [ ! -z "$(pidof dropbearkey)" ] ; do
	sleep 2
	echo -n '.'
    done
    logger -t installer "Info: Ключ ecdsa создан"

    rm /opt/etc/dropbear/dropbear_rsa_host_key
    dropbearkey -t rsa -f /opt/etc/dropbear/dropbear_rsa_host_key -s 1024 > /dev/null &
    while [ ! -z "$(pidof dropbearkey)" ] ; do
	sleep 2
	echo -n '.'
    done
    logger -t installer "Info: Ключ rsa создан"

logger -t installer '[4/5] Установка Entware-Keenetic завершена! Сохранение временной зоны и запуск dropbear...'

timezone=`ndmq -p "show running-config" -P message | awk '/timezone/{print $3}'`
ln -sf /opt/share/zoneinfo/$timezone  /opt/etc/localtime
dropbear -p 22 -a

logger -t installer '[5/5] Настройка сценария запуска для прошивки NDMS...'
ndmq -p 'opkg initrc /opt/etc/init.d/rc.unslung'
ndmq -p 'system configuration save'

logger -t installer 'Готово!!!'
logger -t installer 'Можно открыть SSH-сессию для соединения с устройством (логин:пароль -> root:zyxel).'
rm $0
