#!/opt/bin/sh

export TZ=`cat /etc/TZ | tail -n 1`
export PATH=/opt/sbin:/opt/bin:$PATH
unset LD_LIBRARY_PATH
unset LD_PRELOAD

URL=http://ndm.zyxmon.org/binaries/keenle/installer

case $(mount | grep 'on /opt' | cut -d ' ' -f 5) in
    ext2|ext3)
	echo 'Раздел годен.'
    ;;
    *ntfs*)
	echo 'Раздел NTFS! атрибуты пользователь:группа могут не поддерживаться.'
	echo 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3.'
    ;;
    *hfs*)
	echo 'Раздел с HFS! (не тестировалось).'
	echo 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3.'
    ;;
    *)
        echo 'Используйте накопитель с файловой системой ext2/ext3. Отменяем...'
	exit 1
    ;;
esac

echo '[1/4] Начало установки Entware-Keenetic...'
dots.sh &
# This is for opkg only. The other folders will be created from opt-ndmsv2 package
# Только для opkg. Остальные папки будут созданы пакетом opt-ndmsv2
for folder in lib/opkg tmp var/lock; do
    mkdir -p /opt/$folder
done

# Fix for multiuser environment
chmod 777 /opt/tmp

wget $URL/opkg -O /opt/bin/opkg
chmod +x /opt/bin/opkg
wget $URL/opkg.conf -O /opt/etc/opkg.conf

echo '[2/4] Установка базовых пакетов...'
opkg update
opkg install opt-ndmsv2 dropbear
ldconfig > /dev/null 2>&1

echo '[3/4] Генерация SSH-ключей...'
dbkey () {
# $1 is a key type [rsa|ecdsa]
    rm /opt/etc/dropbear/dropbear_${1}_host_key
    dropbearkey -t $1 -f /opt/etc/dropbear/dropbear_${1}_host_key > /dev/null &
    while [ ! -z "$(pidof dropbearkey)" ] ; do
	sleep 2
	echo -n '.'
    done
    echo 'выполнено.'
}
dbkey rsa
dbkey ecdsa

echo '[4/4] Entware-Keenetic установлен! Запуск dropbear...'
dropbear -p 22 -a

echo 'Можно запускать новую SSH-сессию (логин:пароль -> root:zyxel).'
rm $0