#!/opt/bin/sh

export TZ=`cat /etc/TZ | tail -n 1`
export PATH=/opt/sbin:/opt/bin:$PATH
export LANG='ru_RU.UTF-8'
export LC_ALL='ru_RU.UTF-8'
unset LD_LIBRARY_PATH
unset LD_PRELOAD

URL=http://ndm.zyxmon.org/binaries/keenle/installer

case $(mount | grep 'on /opt' | cut -d ' ' -f 5) in
    ext2|ext3)
	logger 'Info: Раздел пригоден для установки.'
    ;;
    *ntfs*)
	logger 'Info: Раздел NTFS! атрибуты "пользователь:группа" могут не поддерживаться.'
	logger 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3.'
    ;;
    *hfs*)
	logger 'Info: Раздел с HFS! (!не тестировалось!).'
	logger 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3.'
    ;;
    *)
        logger 'Critical error: Используйте накопитель с файловой системой ext2/ext3. Отменяем...'
	exit 1
    ;;
esac

logger '[1/5] Начало развёртывания системы Entware-Keenetic...'

# This is for opkg only. The other folders will be created from opt-ndmsv2 package
# Только для opkg. Остальные папки будут созданы пакетом opt-ndmsv1/2
logger 'Info: Создание папок...'

for folder in lib/opkg tmp var/lock; do
    mkdir -p /opt/$folder
done

# Fix for multiuser environment
chmod 777 /opt/tmp

logger '[2/5] Загрузка и установка базовых пакетов...'
opkg update
opkg install opt-ndmsv2 dropbear ndmq

if [ $? -eq 0 ] ; then
    logger 'Info: Установка пакетов прошла успешно! Продолжаем...'
  else
    logger 'Critical error: Ошибка загрузки? Нет соединения с интернет? Сервер не работает?'
    logger 'Выход из установки...'
    exit 1
fi

ldconfig > /dev/null 2>&1

logger '[3/5] Настройка сценария запуска для прошивки NDMS...'
ndmq -p 'opkg initrc /opt/etc/init.d/rc.unslung'
ndmq -p 'system configuration save'

logger '[4/5] Генерация SSH-ключей...'
dbkey () {
# $1 is a key type [rsa|ecdsa]
    rm /opt/etc/dropbear/dropbear_${1}_host_key
    dropbearkey -t $1 -f /opt/etc/dropbear/dropbear_${1}_host_key > /dev/null &
    while [ ! -z "$(pidof dropbearkey)" ] ; do
	sleep 2
	echo -n '.'
    done
    logger "Info: ключ $1 создан"

}
dbkey rsa
dbkey ecdsa

logger '[5/5] Установка Entware-Keenetic завершена! Запуск dropbear...'
dropbear -p 22 -a

logger 'Готово!!!'
logger 'Можно открыть SSH-сессию для соединения с устройством (логин:пароль -> root:zyxel).'
rm $0